# Generated by Django 4.0.6 on 2022-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='ArticleTag', to='articles.article'),
        ),
    ]
