# Generated by Django 4.0.6 on 2022-08-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articletag_is_main_alter_tag_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='основной'),
        ),
    ]
